openapi: 3.0.0
info:
  title: Uploading of initial data
  version: '1.0'
  description: Uploading of tickets and rules
servers:
  - url: 'http://localhost:3000'
    description: host
paths:
  /upload/rules:
    post:
      summary: ''
      operationId: post-rules-upload
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Rule'
      tags:
        - upload
    parameters: []
  /upload/tickets:
    post:
      summary: ''
      operationId: post-tickets-upload
      responses:
        '200':
          description: OK
      tags:
        - upload
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Ticket'
    parameters: []
  /events/days:
    parameters: []
    get:
      summary: Your GET endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: array
                items:
                  $ref: '#/components/schemas/RuleEvent'
      operationId: get-tickets-days-start-start-finish-finish
      parameters:
        - schema:
            type: string
            format: date
            example: '2011-10-05'
          in: query
          name: from
          description: From which iso format date
        - schema:
            type: string
            format: date
            example: '2011-10-05'
          in: query
          name: to
          description: to which iso format date - on abscene till today
          allowEmptyValue: true
      tags:
        - fetch
  /events/weeks:
    get:
      summary: Your GET endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RuleEvent'
      operationId: get-tickets-weeks
      parameters:
        - schema:
            type: string
            format: date
            example: '2011-10-05'
          in: query
          name: from
          description: From which iso format date
        - schema:
            type: string
            format: date
            example: '2011-10-05'
          in: query
          name: to
          description: to which iso format date - on abscene till today
          allowEmptyValue: true
      tags:
        - fetch
    parameters: []
components:
  schemas:
    Ticket:
      title: Ticket
      type: object
      x-examples:
        example-1:
          id: 0
          title: string
          creation_time: 0
          resolution: TP
          rules:
            - 0
      description: Ticket of several combined rules
      properties:
        id:
          type: string
        title:
          type: string
        creation_time:
          type: number
        resolution:
          type: string
          enum:
            - TP
            - FP
        rules:
          type: array
          items:
            type: string
    Rule:
      x-examples:
        example-1:
          id: 0
          title: string
      title: Rule
      type: object
      properties:
        id:
          type: number
        name:
          type: string
      description: Triggered rule that is connected to tickets
    RuleEvent:
      description: ''
      type: object
      properties:
        ruleName:
          type: string
          minLength: 1
        numTickets:
          type: array
          items:
            type: number
        resolutions:
          type: array
          uniqueItems: true
          minItems: 0
          items:
            type: object
            properties:
              tp:
                type: number
              fp:
                type: number
            required:
              - tp
              - fp
      required:
        - ruleName
        - numTickets
        - resolutions
  securitySchemes: {}
security: []
tags:
  - name: upload
  - name: fetch
